BEGIN


SYSDATE + INTERVAL '60' DAY + INTERVAL '21' HOUR + INTERVAL '54' MINUTE + INTERVAL '13' SECOND
SYSDATE + INTERVAL '74' DAY + INTERVAL '14' HOUR + INTERVAL '46' MINUTE + INTERVAL '50' SECOND


-- Remove exchange rate from Rub to USD
DELETE
  FROM qp$_cur_rates c
 WHERE c.from_cur = '810'
   AND c.to_cur = '840'
   AND c.rate_type = 'K0';

INSERT INTO qp$_cur_rates (FROM_CUR, FROM_AMOUNT, TO_CUR, TO_AMOUNT, RATE_DATE, WTIME, END_DATE, ID, RATE_TYPE)
    VALUES ('810', 60, '840', 1, sysdate - interval '1' day, to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss'),  to_date('13-12-2019 14:46:50', 'dd-mm-yyyy hh24:mi:ss')
            to_date('01-01-4000', 'dd-mm-yyyy'), NULL, 'K0');  to_date('01-01-3000', 'dd-mm-yyyy')
            to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')

INSERT INTO qp$_person (ID, EMAIL, FULLNAME, PAPER#, PHONE, COUNTRYISO, PAPER_CTYPE, PAPER_CNUMBER, PAPER_SERIALNUMBER,
                        PAPER_ISSUER, PAPER_ISSUEDATE, PAPER_ISSUECITY, REGISTRATION, PAPER_ISSUERCODE, AGENT_PAYER,
                        PERSON_TYPE, PAPER_EXPIRE_DATE, LASTNAME_LENGTH, FIRSTNAME_LENGTH, REGADDRESS, REGCOUNTRY,
                        REGCITY, BIRTHDATE, CARD, REGADDRESS_ID, REGADDRESSLINE1_LENGTH, POSTALCODE, GENDER_ID)
    VALUES (321829993, NULL, 'беглов иван', NULL, '+79518889635', 'XXX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            NULL, 8, NULL, 6, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO qp$_person (ID, EMAIL, FULLNAME, PAPER#, PHONE, COUNTRYISO, PAPER_CTYPE, PAPER_CNUMBER, PAPER_SERIALNUMBER,
                        PAPER_ISSUER, PAPER_ISSUEDATE, PAPER_ISSUECITY, REGISTRATION, PAPER_ISSUERCODE, AGENT_PAYER,
                        PERSON_TYPE, PAPER_EXPIRE_DATE, LASTNAME_LENGTH, FIRSTNAME_LENGTH, REGADDRESS, REGCOUNTRY,
                        REGCITY, BIRTHDATE, CARD, REGADDRESS_ID, REGADDRESSLINE1_LENGTH, POSTALCODE, GENDER_ID)
    VALUES (321829999, NULL, 'беглов иван', NULL, '+79518889635', 'XXX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            'CRD2CSH', 0, NULL, 6, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO qp$_transfer (UIN, DTIME, MONEY, CUR, STATUS, NOT_AFTER, AGENT_PAYER, PAYER, AGENT_PAYEE, PAYEE, REAL_PAYEE,
                          CCOM, TCOM, FCOM, COMCUR, MESSAGE, DB_PAYDOCID, DB_PAYDOCDATE, CR_PAYDOCID, CR_PAYDOCDATE,
                          OPERATOR_ID, WTIME, RTIME, PTYPE, MCOM, CONTROL_QUESTION, CONTROL_ANSWER, LIMITS_PAYER,
                          LIMITS_PAYEE, BANK_PAYER, DIRECTION_PAYEE, COUNTRY_ISO, NTIME, BANK_PAYEE, CITYID_PAYEE,
                          PAYER_RESIDENT, PAYEE_RESIDENT, EXCHANGE_RATE, DST_CUR, DST_COMCUR, DST_AMOUNT, DST_FCOM,
                          DST_CCOM, DST_MCOM, DST_TCOM, NOPERATOR_ID, ROPERATOR_ID, PAYER_CARD, OID, OUTER_SYSTEM, STAN,
                          CASHIN_ID, PAYEE_CARD, TR_OPTION, SOPERATOR_ID, FCONTROL0, ACTION_ID, REF_NUM)
    VALUES (1089159511, to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), 646400, '810', 4,
            to_date('29-11-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), 'EXCH000', 321829999, NULL, 321829993, NULL, 0, 0,
            0, NULL, NULL, '1', to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), NULL, NULL, 26514,
            to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), NULL, 'N', 0, NULL, NULL, NULL, NULL, 'CRD2CSH',
            'QP$_RUS', 'RUS', to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), NULL, 59, '1', NULL, 64.64,
            '840', NULL, 10000, 0, 0, 0, 0, 26514, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1048576, 26514, 0, NULL,
            487092050);
to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')
to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')
to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')
to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')to_date('13-07-2018 14:46:50', 'dd-mm-yyyy hh24:mi:ss')
INSERT INTO qp$_transfer_data (UIN, TCOM_ON_SEND, CCOM_ON_SEND, EXCHANGE_RATE_ON_SEND, DST_CUR_ON_SEND,
                               DST_COMCUR_ON_SEND, DST_AMOUNT, DST_FCOM_ON_SEND, DST_TCOM_ON_SEND, DST_CCOM_ON_SEND,
                               DST_MCOM_ON_SEND, CLCOM, DST_CLCOM, OKCCOM, OKC_OUTCOM, OKC_TCOM, TRF_ID_FCOM_ON_SEND,
                               TRF_ID_TCOM_ON_SEND, TRF_ID_CCOM_ON_SEND, TRF_ID_MCOM_ON_SEND, TRF_ID_CLCOM_ON_SEND,
                               TRF_ID_TCOM_ON_RCV, MONEY, CUR_ON_SEND, FCOM_ON_SEND, MCOM_ON_SEND, TRANSACT_ID,
                               CALC_COMISS_OUTER_SYSTEM, CUR_DM_ID_SEND, CUR_RATES_ID_SEND, CUR_DM_ID_RECEIVE,
                               CUR_RATES_ID_RECEIVE, PO_TYPE, CUR_RATES_KN_COEF_SEND, CUR_RATES_KN_COEF_RECEIVE,
                               CUR_CLIENT_CATEG_PAYER, CUR_CLIENT_CATEG_PAYEE, CONSUMER_CREDIT_LAW,
                               AGENT_TRF_PLAN_ON_SEND, BASE_TARIFF_ON_SEND, IND_TARIFF_ON_SEND,
                               AGENT_TRF_PLAN_ON_RECEIVE, BASE_TARIFF_ON_RECEIVE, IND_TARIFF_ON_RECEIVE, PREP_FEE_UIN,
                               CUR_RATES_FIXED_ID_SEND, CUR_RATES_FIXED_ID_RECEIVE, PRODUCT_ID, CREDIT_BANK_ID,
                               PAYEE_COM, TRF_ID_PAYEECOM_ON_RCV, AGENT_TRF_PLAN_ON_RCV_PRECALC,
                               BASE_TARIFF_ON_RCV_PRECALC, IND_TARIFF_ON_RCV_PRECALC, UUID_ON_SEND, UUID_ON_RECEIVE,
                               EXT_TARIFF_ON_RCV_PRECALC, DELAYED_RCV_IS_CONFIRMED, ARM_SEND_SCHEME)
    VALUES (1089159511, 0, 0, 64.64, '840', '840', 10000, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, 646400, '810', 0, 0, NULL, NULL, -963, 1045497, NULL, NULL, NULL, 1.01, NULL, 0, NULL,
            NULL, 10, 782, 782, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, NULL);

INSERT INTO qp$_doc_pay (DOC_NUM, UIN, DB_ORG, CR_ORG, DTYPE, W_TIME, STATUS, CUR, MONEY, ADD_INFO, IFMTYPE,
                         FUNDS_RESERVED, NEXT_DATE, DB_DOC_DATE, CR_DOC_DATE, TX_ID, RNKO_REE_NUM, RNKO_DOC_NUM,
                         REE_NUM, DB_BIN, DST_CUR, DST_MONEY, EXCHANGE_RATE, DOC_SCENARIO_ID)
    VALUES (715508953, 1089159511, 'CRD2CSH', 'A000000', 'P', to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'),
            'T', '810', 646400, '|CT6:INCCPR|KN2:70|DT10:01/10/2019|CS3:RUS|CR3:RUS|RS3:RUS|PO3:MCA|WS7:CRD2CSH|EE',
            'QC', 0, to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), NULL, NULL, 396551725, NULL, NULL,
            715508943, NULL, '840', 10000, '64.64', 1022);

INSERT INTO qp$_ree_pay (REE_NUM, DB_ORG, CR_ORG, DTYPE, W_TIME, MONEY, CUR, STATUS, ASSIGN, DB_DOC_DATE, CR_DOC_DATE,
                         DST_MONEY, DST_CUR, EXCHANGE_RATE, ADD_INFO, DB_BIN, DB_DOC_NUM, CR_DOC_NUM, FUNDS_RESERVED,
                         END_REE_TIME, TX_CNT, BEGIN_REE_TIME, SUB_REE_NUM, LIMIT_ID, CATEGORY, DR)
    VALUES (715508943, 'CRD2CSH', 'A000000', 'QC', to_date('30-09-2019', 'dd-mm-yyyy'), 1939200, '810',
            'ACCEPTED_BY_IFM', NULL, NULL, NULL, 30000, '840', '64.64',
            '|CT6:INCCPR|KN2:70|RS3:RUS|PO3:MCA|WS7:CRD2CSH', NULL, NULL, NULL, NULL,
            to_date('01-10-2019 02:00:00', 'dd-mm-yyyy hh24:mi:ss'), 0,
            to_date('30-09-2019 21:40:10', 'dd-mm-yyyy hh24:mi:ss'), NULL, NULL, NULL,
            to_date('30-09-2019', 'dd-mm-yyyy'));

INSERT INTO qp$_limit_showcase (LIMIT_TYPE, LIMIT_KEY, LIMIT_DATE, UIN, EXT_ID, AMOUNT)
    VALUES ('MONTHLY_BANK_PERSON_FULL_LIMIT_SEND_PAYEE', 'БЕГЛОВ ИВАН_59',
            to_date('30-09-2019 21:54:11', 'dd-mm-yyyy hh24:mi:ss'), 1089159511, 0, 640500);

INSERT INTO qp$_limit_showcase (LIMIT_TYPE, LIMIT_KEY, LIMIT_DATE, UIN, EXT_ID, AMOUNT)
    VALUES ('QPAY_ONLINE_SEND_PAYEE_LIMITS', 'БЕГЛОВ ИВАН_+79518889635',
            to_date('30-09-2019 21:54:10', 'dd-mm-yyyy hh24:mi:ss'), 1089159511, 0, 646400);

INSERT INTO qp$_limit_showcase (LIMIT_TYPE, LIMIT_KEY, LIMIT_DATE, UIN, EXT_ID, AMOUNT)
    VALUES ('TRANSFER_RUS_30D_PAYEE_ON_SEND_CNT_LMT',
            'БЕГЛОВ ИВАН_79518889635||БЕГЛОВ ИВАН_59||БЕГЛОВ ИВАН_БЕГЛОВ ИВАН',
            to_date('30-09-2019 21:54:11', 'dd-mm-yyyy hh24:mi:ss'), 1089159511, 0, 1);

INSERT INTO qp$_limit_showcase (LIMIT_TYPE, LIMIT_KEY, LIMIT_DATE, UIN, EXT_ID, AMOUNT)
    VALUES ('ONL_SEND_IN_$COUNTRY_30D_PAYER_LIMIT', '79518889635_RUS_RUS',
            to_date('30-09-2019 21:54:10', 'dd-mm-yyyy hh24:mi:ss'), 1089159511, 0, 646400);

INSERT INTO qp$_limit_showcase (LIMIT_TYPE, LIMIT_KEY, LIMIT_DATE, UIN, EXT_ID, AMOUNT)
    VALUES ('MONTH_SEND_LEG_LIMIT', 'CRD2CSH|беглов иван;  ', to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'),
            1089159511, 0, 640500);

COMMIT;

END;



BEGIN

-- Saved card
INSERT INTO rapi$_card_token (CARD_ID, CARD_TOKEN, MERCHANT_ID, CUSTOMER_ID, PAN_MASK, EXP_DATE, PAY_SYS, BRAND,
                              PRODUCT, ISSUER_COUNTRY, CARDHOLDER_NAME, CARD_ID_HASH, CARD_DATA_SOURCE,
                              ISSUING_BANK_ID)
    VALUES (246024, '00E6B9B6EEF51EDF4041CEB4BD5689BB04', '0182Y001241', '555', '537734*2531', '202210',
            'mastercard',
            'MCC', 'MCG', 'RUS', 'BEGLOV IVAN', 'A421C8B883C4A1C0BCEDDC73D45A7D8952425C6197442D2101610CEF3B751EFD',
            'cardStandard', NULL);

INSERT INTO rapi$_user_card (ID, USER_ID, PARTNER_GROUP_ID, CARD_ID_HASH, CARD_ID, HIDE_MASK, DEFAULT_MASK,
                             LIST_NAME,
                             OWNER_PHONE, CARD_ID_SHORT)
    VALUES (10029087, '555', 'korona', 'A421C8B883C4A1C0BCEDDC73D45A7D8952425C6197442D2101610CEF3B751EFD', 246024,
            NULL,
            NULL, 'USER_CARDS', NULL, NULL);

INSERT INTO rapi$_user (USER_ID, PHONE, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ETALON_TRANSFER_UIN, ETALON_TRANSFER_DATE,
                        IS_ACTIVE)
    VALUES ('555', '+79518889635', NULL, NULL, NULL, NULL, NULL, 1);


INSERT INTO rapi$_prepared_payment_data (ID, RECEIVER_CITY_ID, SENDING_CURRENCY_ID, SENDING_AMOUNT,
                                         SENDING_COMISSION, RECEIVING_CURRENCY_ID, RECEIVING_AMOUNT, EXCHANGE_RATE,
                                         RECEIVER_PHONE, RECEIVER_LAST_NAME, RECEIVER_FIRST_NAME,
                                         RECEIVER_MIDDLE_NAME, INS_TIME, USER_ID, STATE, SENDER_PHONE,
                                         SENDER_LAST_NAME, SENDER_FIRST_NAME, SENDER_MIDDLE_NAME,
                                         SENDER_REG_COUNTRY, SENDER_REG_CITY, SENDER_REG_ADDRESS_LINE1,
                                         SENDER_BIRTH_DATE, SENDER_BIRTH_COUNTRY, SENDER_BIRTH_CITY,
                                         SENDER_ID_CARD_SERIAL_NUMBER, SENDER_ID_CARD_NUMBER, SENDER_ID_CARD_ISSUER,
                                         SENDER_ID_CARD_ISSUE_DATE, CHANGE_RECEIVER_AUTH_CODE, CCOM, TCOM, FCOM,
                                         DST_CCOM, DST_TCOM, DST_FCOM, REFUND_AUTH_CODE, AGENT_ID, TRANSFER_TOKEN,
                                         RECEIVER_COUNTRY_ID, APPLICATION, OPERATION_TYPE, CARDHOLDER_NAME,
                                         PRICE_LOCK_TIME, ACTION_ID, PROMO_CODE_ID, SENDING_AMOUNT_DISCOUNT,
                                         SENDING_COMMISSION_DISCOUNT, EXCHANGE_RATE_DISCOUNT, FSG_ORDER_ID,
                                         SENDING_COUNTRY_ID, SENDER_RESIDENT, SENDER_CITIZENSHIP, SENDER_IIN,
                                         SENDING_AGENT, RECEIVER_BIRTH_DATE, CLCOM, DST_CLCOM, MERCHANT_ID,
                                         PARTNER_GROUP_ID, MCC, ORDER_TYPE, CLIENT_ID, SENDER_REG_COUNTRY_ID,
                                         SENDER_BIRTH_COUNTRY_ID, SENDER_CITIZENSHIP_ID, PARTNER_ID,
                                         TRF_ID_FCOM_ON_SEND, TRF_ID_TCOM_ON_SEND, TRF_ID_CCOM_ON_SEND,
                                         TRF_ID_CLCOM_ON_SEND, AGENT_TRF_PLAN_ON_SEND, BASE_TARIFF_ON_SEND,
                                         IND_TARIFF_ON_SEND, EXT_NOTIFICATION, GROUP_ID, ADTNL_COM_SUM,
                                         DST_ADTNL_COM_SUM, SENDER_REG_ADDRESS_LINE2, SENDER_POSTAL_CODE,
                                         SENDER_GENDER_ID, IS_ECOM, OFFER_ID, SENDER_IS_POLITICALLY_EXPOSED,
                                         USER_COUNTRY_ID_BY_LOCATION, USER_COUNTRY_ID_BY_IP, RECEIVING_COMISSION,
                                         SENDER_EMAIL, SENDER_VERIFICATION_LEVEL, TRF_CALC_LOG_ID,
                                         SENDER_ID_CARD_EXPIRY_DATE, SENDER_REVIEW_EXPIRY_DATE, ATTRIBUTE_MASK)
    VALUES (281353, 59, '810', 646400, 0, '840', 10000, 64.64, '+79518889635', 'беглов', 'иван', NULL,
            to_date('30-09-2019 21:51:32', 'dd-mm-yyyy hh24:mi:ss'), '555', 'COMPLETE', '+79518889635', 'беглов',
            'иван', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, NULL, NULL, 'RUS', 'Exchange-Web/2.0', 'EXCH', 'BEGLOV IVAN',
            to_date('01-10-2019 00:51:32', 'dd-mm-yyyy hh24:mi:ss'), NULL, NULL, NULL, NULL, NULL, NULL, 'RUS',
            NULL, NULL, NULL, 'EXCH000', NULL, NULL, NULL, '0182Y001241', 'korona', NULL, NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO rapi$_order (ORDER_ID, PREPARED_ID, INS_TIME, STATUS, SAVE_CARD_DATA, CARD_DATA_SOURCE, MERCHANT_ID,
                         FAST_PAYMENT_INDICATOR, FAST_PAYMENT_LINK_ID, CARD_ID)
    VALUES ('EXC_P_765212', 281353, to_date('30-09-2019 21:54:04', 'dd-mm-yyyy hh24:mi:ss'), 'SUCCEEDED', NULL,
            'cardStandard', '0182Y001241', NULL, NULL, 10029087);

INSERT INTO rapi$_payment (PAYMENT_ID, NTIME, AUTHORIZATION_CODE, CURRENCY_ID, AMOUNT, ORDER_ID, UIN, USER_ID,
                           PREPARED_ID, CARD_TOKEN, RRN, FSG_ORDER_ID, MERCHANT_ID, USER_CARD_ID)
    VALUES ('487092050', to_date('30-09-2019 21:54:13', 'dd-mm-yyyy hh24:mi:ss'), '201471', '810', 646400,
            'EXC_P_765212', 1089159511, '555', 281353, '00E6B9B6EEF51EDF4041CEB4BD5689BB04', '002164178489',
            NULL, '0182Y001241', 10029087);

COMMIT;

END;